<?php return array (
  'installed' => 'belum lah tolo',
  'servername' => '',
  'username' => '',
  'password' => '',
  'dbname' => '',
  'nama_website' => 'KNTLCMS Website',
  'desc_website' => 'ini adalah instalasi KNTLCMS',
  'gambar_default' => 'https://i.imgur.com/qv2t3kv.png',
  'bootstrap_theme' => 'https://getbootstrap.com/docs/3.3/dist/css/bootstrap.min.css',
  'prefix_nama' => 'ada',
  'web_mode' => 'entri',
  'prefix_entri' => '',
  'prefix_acak' => '',
  'sufix_acak' => '',
  'acak_range_start' => '0',
  'acak_range_end' => '100',
  'reg_nama' => 'KNTLCMS SUDAH OPEN SOURCE . TIDAK PERLU REGISTRASI LAGI!',
  'reg_kode' => '830e38e0d318ffe0314bc87d955860b8',
  'baon' => 'kontol',
);